a = input('Digite algo: ')
print ('o tipo primitivo deste valor é ',type(a))
print('Só tem espaços? ', a.isspace())
print('Só é um numero? ', a.isnumeric())
print('Só é um alphabeto? ', a.isalpha())
print('Só é um alphanumérico? ', a.isalnum())
print('Só está em maiusculas? ', a.isupper())
print('Só está em mainusculas? ', a.islower())
print('Só está capitalizada? ', a.istitle())