nome = str(input('Digite seu nome completo: ')).strip()
print('analisando seu nome...')
print('seu nome em maiuscula é {}'.format(nome.upper()))
print('seu nome em minuscula é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format (len(nome)-nome.count(' ')))
print('seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('seu primeiro nome é {} e ele tem {} letras'.format(separa [0], len(separa[0])))
